packages:
  - apps/*
  - packages/*
catalog:
  zod: ^4.0.2
  "@trpc/server": ^11.5.0
  "@trpc/client": ^11.5.0
  better-auth: ^1.3.28
  "@polar-sh/better-auth": ^1.1.3
  drizzle-orm: ^0.44.2
  dotenv: ^17.2.2
